language: rust

# cache: cargo

rust:
  # - stable
  # - beta
  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly

script:
  - rustup component add rustfmt
    # concurrent test causes port conflict
  - cargo test --verbose --all -- --test-threads=1

notifications:
  email:
    on_success: change
    on_failure: always
