# generate table of content.
# See:
# https://github.com/ekalinin/github-markdown-toc
toc:
	gh-md-toc --insert replication-algo.md
	# nmp install -g prettier
	prettier --write --print-width 80 --prose-wrap preserve **/*.md
